title: Azure Red Hat OpenShift Integration
description: This lab walks you through the creation of a Azure Red Hat OpenShift cluster and the integration of Azure services with the cluster.
theme: just-the-docs

aux_links:
  "Azure Red Hat OpenShift Integration lab on GitHub": 
    - "https://github.com/erleonard/aro-deployment"

enable_copy_code_button: true

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

last_edit_timestamp: true 
last_edit_time_format: "%b %e %Y at %I:%M %p"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/erleonard/aro-deployment"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"