title: Azure Red Hat OpenShift Integration
description: This lab walks you through the creation of a Azure Red Hat OpenShift cluster and the integration of Azure services with the cluster.
theme: just-the-docs

# url: https://just-the-docs.github.io

aux_links:
  "Azure Red Hat OpenShift Integration lab on GitHub": 
    - "https://github.com/erleonard/aro-deployment"


callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
