name: aro-destroy
on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: 'Delete ARO cluster service principal'
      run: |
          arosp=$(az aro show --name arocluster --resource-group aro-rg --query servicePrincipalProfile.clientId -o tsv)
          az ad sp delete --id $arosp
    - name: 'Delete ARO cluster'
      run: |
          az aro delete --name arocluster --resource-group aro-rg --yes